apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: codefresh
patches:
- path: ingress-patch.json
  target:
    group: apps
    kind: Deployment
    name: argo-server
    version: v1
resources:
- ../../base
- ingress.yaml
- rbac.yaml
- artifact-repo.yaml
patchesStrategicMerge:
- |
  apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: argo-server
- |
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: workflow-controller-configmap
  data:
    workflowDefaults: |
      spec:
        serviceAccountName: workflow     
